# Generated by Django 5.1.6 on 2025-03-03 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CityStars_app', '0002_remove_chat_users_chat_friendship_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
