# Generated by Django 5.1.6 on 2025-03-03 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityStars_app', '0004_alter_message_user_alter_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='friendship',
        ),
        migrations.AlterField(
            model_name='friendship',
            name='user_initiated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_initiated', to='CityStars_app.profile'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='user_requested',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requested', to='CityStars_app.profile'),
        ),
        migrations.AddField(
            model_name='chat',
            name='friendship',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CityStars_app.friendship'),
        ),
    ]
