# Generated by Django 5.1.6 on 2025-03-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CityStars_app', '0004_profile_slug'),
    ]

    operations = [
    ]
