# Generated by Django 2.2.28 on 2025-03-04 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CityStars_app', '0005_remove_chat_friendship_and_more'),
        ('CityStars_app', '0002_auto_20250303_1115'),
    ]

    operations = [
    ]
