# Generated by Django 5.1.6 on 2025-03-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityStars_app', '0005_remove_chat_friendship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='desc',
            field=models.CharField(default='', max_length=300),
        ),
    ]
