# Generated by Django 5.1.6 on 2025-03-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityStars_app', '0005_remove_chat_friendship_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='avg_rating',
            new_name='rating',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
