# Generated by Django 5.1.6 on 2025-03-14 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CityStars_app', '0005_alter_profile_profile_picture'),
        ('CityStars_app', '0005_auto_20250313_1540'),
    ]

    operations = [
    ]
