# Generated by Django 5.1.6 on 2025-03-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityStars_app', '0006_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_images/DEFAULT_profile_photo.jpg', upload_to='profile_images'),
        ),
    ]
