# Generated by Django 5.1.6 on 2025-03-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityStars_app', '0006_city_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='avg_rating',
            new_name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
