# Generated by Django 5.1.6 on 2025-03-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityStars_app', '0007_rename_avg_rating_post_likes_post_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=15),
        ),
    ]
